id: P290D0B02
initial_creation_type: input
source_metadata:
  title: Vajrāyudha
  language: es
  description: 'Texts by the master Vajrāyudha/Vajraśastra (rdo rje mtshon cha):'
  volume:
    3784faee38114efbb32ba3c399379b42:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Mañjuśrī
created_at: '2022-03-01T02:25:45.897821'
last_modified_at: '2022-03-01T02:25:45.897823'
